# This is a basic workflow to help you get started with Actions

name: IssueComment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the branch1 branch
  issue_comment:
    types: [created, deleted]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  AddToAssociationFile:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: ${{ startsWith( github.event.comment.body, 'Fixed By' ) }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set PR Link
        id: setpr
        run: |
          echo ::set-output name=pr_link::$(echo ${{ github.event.comment.body }} | awk '{print $NF}')
          
      - name: Get PR Link
        id: getpr
        run: |
          echo ${{ steps.setpr.outputs.pr_link }}
          
      - name: Checkout Project
        uses: actions/checkout@v2
        with:
          path: .
          
      - name: echo to file
        run: |
          FILE=./files/mapping.txt
          echo 'hello' > $FILE
          
      - name: Push Project B
        run: |
          cd ./files
          git add ./mapping.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -am "Updating Associations File"
          git push
  

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
