# This is a basic workflow that is manually triggered

name: Security Statement Maker

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      CVE-ID:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'ID of the CVE'
        # Default value if no value is explicitly provided
        default: ''
        # Input has to be provided for the workflow to run
        required: true
      Statement:
        description: 'statement text'
        default: ''
        required: true
      Product:
        description: 'Product of the Vuln'
        default: ''
        required: true
      VulnDescription:
        description: 'vulnerability description'
        default: ''
        required: false
      ExternalReference:
        description: 'Link to Details'
        default: ''
        required: false
      Verions:
        description: 'Vulnerable Versions'
        default: ''
        required: true
      Status:
        description: 'Status of this vulnerable on our product'
        default: ''
        required: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  AddNewStatementFile:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      - name: Install JQ
        run: |
          sudo apt install jq
        
      - name: Example
        run: echo "Hello ${{ github.event.inputs.CVE-ID }}, your age is ${{github.event.inputs.statement}}"
    
      - name: Checkout Project
        uses: actions/checkout@v2
        with:
          path: .
          
      - name: Make File
        run: |
          touch "./files/${{github.event.inputs.CVE-ID}}-${{github.event.inputs.Product}}.json"
          echo '{"id":"${{ github.event.inputs.CVE-ID }}","description":"${{github.event.inputs.VulnDescription}}","references":"${{github.event.inputs.ExternalReference}}","product":"${{github.event.inputs.Product}}","verions":"${{github.event.inputs.Verions}}","status":"${{github.event.inputs.Status}}","statement":"${{github.event.inputs.Statement}}"}' > "./files/${{github.event.inputs.CVE-ID}}-${{github.event.inputs.Product}}.json"
          jq . "./files/${{github.event.inputs.CVE-ID}}-${{github.event.inputs.Product}}.json" > "./files/${{github.event.inputs.CVE-ID}}-${{github.event.inputs.Product}}.json"
          
      - name: Commit Change
        run: |
          git add "./files/${{github.event.inputs.CVE-ID}}-${{github.event.inputs.Product}}.json"
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -am "Adding New Statement json"
          git push
      
